stages:
  - build
  - migration
  - start

build:
  tags:
  - dev
  stage: build
  script:
    - dotnet build
    - pwd
    - ls -all
  artifacts:
    untracked: true
    when: on_success
    paths:
      - "bin/"
      - "obj/"


migration:
  tags:
  - dev
  stage: migration
  script:
    - dotnet ef database update
    - pwd
    - ls -all
