stages:
  - build
  - test
  - deploy

print_build:
  stage: build
  script:
    - echo "Building the application..."

print_test:
  stage: test
  script:
    - echo "Running tests..."

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
  only:
    - master
