stages:
  - build
  - migration
  - publish

build:
  tags:
  - dev
  stage: build
  script:
    - dotnet build
    - pwd
    - ls -all
  artifacts:
    untracked: true
    when: on_success
    paths:
      - "bin/"
      - "obj/"

migration:
  tags:
  - dev
  stage: migration
  script:
    - dotnet ef database update
    - pwd
    - ls -all
  artifacts:
    untracked: true
    when: on_success
    paths:
      - "bin/"
      - "obj/"

publish_and_start:
  tags:
  - dev
  stage: publish
  script:
    - dotnet publish --configuration Release
    - sudo systemctl enable hisobot.service
    - sudo systemctl start hisobot.service
    - sudo systemctl restart hisobot.service
  artifacts:
    untracked: true
    when: on_success
    paths:
      - "bin/"
      - "obj/"