stages:
  - build
  - migration
  - start

build:
  tags:
  - hisobot
  stage: build
  script:
    - dotnet build
    - pwd
    - ls -all

migration:
  tags:
  - hisobot
  stage: migration
  script:
    - pwd
    - ls -all
