stages:
  - build
  - publish
  - deployment

build:
  tags:
  - dev
  stage: build
  script:
    - sudo cp /home/otabek/gireporterappsettings/* ./GIReporter/ -r
    - dotnet build
    - dotnet ef database update --project GIReporter

publish:
  tags:
  - dev
  stage: publish
  script:
    - dotnet publish --configuration Release
    - sudo cp ./GIReporter/bin/Release/net7.0/* /home/gi-reporter/ -r 

deployment:
  tags:
  - dev
  stage: deployment
  script:
    - sudo systemctl restart gi-reporter.service 