stages:
  - build
  - migration
  - start

build:
  tags:
  - hisobot
  stage: build
  script:
    - dotnet build

migration:
  tags:
  - hisobot
  stage: migration
  script:
    - dotnet ef database update
